# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/vga_mem/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/vga_mem/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/vga_mem/vga_mem.xci
# IP: The module: 'vga_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/vga_mem/vga_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
