# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315.xci
# IP: The module: 'clk_315' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315.xci
# IP: The module: 'clk_315' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Hector/Desktop/Winter_2023/ECE_540/Labs/FinalProject/Vivado/Vivado.srcs/sources_1/ip/clk_315/clk_315_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_315'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
